### ISSUE TITLE
Could you please upgrade to ember 2.17.0?

### ISSUE THREAD

**Issue by gaur-associates** [dgeb/grunt-ember-templates#100]
Hi,

I rely on grunt-ember-templates. Could you please upgrade to ember 2.17.0?

regards,
Yogi
http://gaurassociates.com/

**Comment by zoltan-nz** [comment]
Hey @gaur-associates, thanks for your comment and reminder. I check it out today and upgrade it to be compatible with the latest versions. Thanks again and Merry Christmas! :)

**Comment by gaur-associates** [comment]
Hi,Thank you very much!! 
I appreciate it a lot. Merry Christmas!!

regards,
Yogi
http://gaurassociates.com/

**Comment by zoltan-nz** [comment]
Hey @gaur-associates v1.1.2 is released with Ember v2.17 compatibility: https://www.npmjs.com/package/grunt-ember-templates

Could you please test it in your project and let me know how is it going?

Thanks, Zoltan

**Comment by gaur-associates** [comment]
Thanks Zoltan,

I was able to upgrade to v1.1.2 and ember v2.17 easily and it works perfectly for my project.

regards,
Yogi
http://gaurassociates.com/
