### ISSUE TITLE
Error log doesn't show the problematic filename

### ISSUE THREAD

**Issue by ronaldocpontes** [dgeb/grunt-ember-templates#36]
Hi,

This is what I get:

Running "emberTemplates:dist" (emberTemplates) task
    Warning: Encoding::UndefinedConversionError on line ["654"] of C: "\x90" to UTF-8 in conversion from Windows-1252 to UTF-8
Run with --trace to see the full backtrace Use --force to continue.

I am using inside a grunt server task but using --trace doesn't make any difference in the output

**Comment by zoltan-nz** [comment]
@ronaldocpontes I hope, this is not a problem any more. :) I close this issue.
