### ISSUE TITLE
How to specify multiple templateBasePath with Reg Expression ?

### ISSUE THREAD

**Issue by cwiese** [dgeb/grunt-ember-templates#64]
I have two "base" directories for my templates (one in app and one is a set of copied vendor templates present in tmp/transpiled/templates) ...How to I indicate multiple base paths?

templateBasePath: /app\/|\/tmp\/transpiled\/app\/templates\//,

**Comment by zoltan-nz** [comment]
@cwiese @MikaelColliander @ErunamoJAZZ if you are still using this package in your ember project, could you please test the new v1.0?

I'm just wondering, what would be the ideal solution for managing multiple BasePath?

**Comment by ErunamoJAZZ** [comment]
Since we are using ember-cli, we don't use grunt anymore, so idk.
