### ISSUE TITLE
Add an option to print the output in CommonJS style

### ISSUE THREAD

**Issue by joeyespo** [dgeb/grunt-ember-templates#65]
Similar to [the AMD issue](https://github.com/dgeb/grunt-ember-templates/issues/34), original Handlebars supports CommonJS style output using `--commonjs` or `-c`.

This should allow the same.

**Comment by zoltan-nz** [comment]
@joeyespo Thanks for the idea. I'm just wondering, is this still could be requirement? With the `templateRegistration` option, the output is freely customizable. 

```
options: {
  templateRegistration: function(name, contents) {
    return "define('templates/" + name + "', ['ember'], function(Ember) { return " + contents + "; });";
  }
}
```

I would close this issue now, however if this is still would be a commonly used feature, we can think about the proper implementation.
