### ISSUE TITLE
Errors don't show where they are occurring

### ISSUE THREAD

**Issue by Frozenfire92** [dgeb/grunt-ember-templates#66]
Hello. I'm running into an error when compiling my templates and it doesn't provide any useful information as to where the error is occurring.

```
Warning: Running "emberTemplates:dist" (emberTemplates) task
    >> Error: if doesn't match each
    Warning: Ember Handlebars failed to compile ... Use --force to continue.
```

It would be nice if it told me what line is causing this error. I've manually searched my template and it appears all of my if/else/each match each other (other colleagues have confirmed too).

**Comment by zoltan-nz** [comment]
The v1.0 of this package uses the official `ember-template-compiler.js` which shows very useful error messages.
