### ISSUE TITLE
Ember-template-compiler version conflict

### ISSUE THREAD

**Issue by bkCDL** [dgeb/grunt-ember-templates#78]
When upgrading my Ember instance to 1.9.1 which I run within Yeoman, I noticed that the [ember-template-compiler](https://github.com/toranb/ember-template-compiler) is on version 1.8.0 while grunt-ember-templates' **package.json** expects 1.9.0-alpha, e.g.:

    "devDependencies": {
        ...
        "ember-template-compiler": "~1.9.0-alpha"
      },

I don't know why the compiler went from 1.9 to 1.8, but my npm installer doesn't like the conflict. 

Bryan

**Comment by dgeb** [comment]
I just published grunt-ember-templates v0.5.0, which uses the 1.9.0-alpha ember-template-compiler and should be compatible with ember 1.10. If you need to use an older version of ember, try v0.4.23 of grunt-ember-templates.
