### ISSUE TITLE
New release with latest changes?

### ISSUE THREAD

**Issue by huguesdk** [dgeb/grunt-ember-templates#79]
Hello,

Since Ember.js 1.9, when using the `templateCompilerPath` and `handlebarsPath` options, this task fails with the following error:

    >> ReferenceError: module is not defined
    Warning: Ember Handlebars failed to compile templates/dummy_template.hbs. Use --force to continue.

It works fine though with the latest changes in the master, even with Ember.js 1.10.

Is a new release to NPM planned soon?

Thanks.

**Comment by dgeb** [comment]
Just published v0.5.0 with HTMLBars as the default! Let me know if you have any problems.

**Comment by huguesdk** [comment]
Wow, that was fast! Works like a charm now, thanks!
