### ISSUE TITLE
Does not work for ember versions > 1.9.1

### ISSUE THREAD

**Issue by ryanmurakami** [dgeb/grunt-ember-templates#81]
Starting in v1.10, Ember is distributing the ember-template-compiler with the ember install. 
grunt-ember-templates uses the ember-template-compiler package on npm, which is stuck at 1.9. 
Do you have any plans to work out compatibility for newer versions of Ember? 
Otherwise, I'd suggest making a note on your Readme.

**Comment by rwjblue** [comment]
It is possible to precompile 1.10+ templates with this library, see https://github.com/dgeb/grunt-ember-templates/pull/77 and https://github.com/dgeb/grunt-ember-templates/pull/80 for more details on how to do this.

**Comment by ryanmurakami** [comment]
You're a lifesaver, @rwjblue. Thanks!
I needed to upgrade grunt-ember-templates to 0.5.0, then add templateCompilerPath and handlebarsPath to the options hash in my Gruntfile.js.
Still seems like something to call out as a special case in regards to versioning, in my opinion.

**Comment by dgeb** [comment]
Closed via https://github.com/dgeb/grunt-ember-templates/pull/82
