### ISSUE TITLE
Window not defined

### ISSUE THREAD

**Issue by fean** [dgeb/grunt-ember-templates#83]
Hi,

I'm trying to pre-compile my templates in Grunt with your module. It works perfectly on Ember 1.9 but now we want to upgrade to the latest version of Ember. That's why I tried to use your module as described with the `ember-template-compiler.js` from downloaded from [here](http://builds.emberjs.com/tags/v1.11.3/ember-template-compiler.js).

This is how the task is setup:

```Javascript
module.exports = function (grunt) {
    grunt.initConfig({
        emberTemplates: {
            'default': {
                options: {
                    templateName: function (sourceFile) {
                        return sourceFile.replace('Views/Handlebars/', '').replace('.hbs', '');
                    },
                    templateCompilerPath: 'JS/libs/ember-template-compiler.js',
                    templateNamespace: 'HTMLBars',
                    handlebarsPath: 'JS/libs/handlebars-v3.0.1.js'
                },
                files: {
                    'JS/Templates.js': ['Views/Handlebars/*.hbs']
                }
            }
        }
    });

	//Load the Ember template compiler
	grunt.loadNpmTasks('grunt-ember-templates');

	//Register default grunt task
	grunt.registerTask('default', ['emberTemplates']);
};
```

But when I execute Grunt then this error occurs:

```
Running "emberTemplates:default" (emberTemplates) task
>> ReferenceError: window is not defined
Warning: Ember Handlebars failed to compile Views/Handlebars/addtrack.hbs. Use --force to continue.

Aborted due to warnings.
```

**Comment by zoltan-nz** [comment]
@fean This package is updated to v1.0 which removed the old dependencies and uses the official ember-template-compiler.js. If you still using grunt instead of ember-cli and you can test this new version, please share your experience. Cheers. :)
