### ISSUE TITLE
template compilation with ember 2.0.0 fails

### ISSUE THREAD

**Issue by novtor** [dgeb/grunt-ember-templates#86]
Console output:

>> Error: no global: `self` or `global` found

Ember 2.0.0
EmberData: 2.0.0
Handlebars: 3.0.3 (tried with 2.0.0 also)

**Comment by leafrabbit** [comment]
My projects have taken place in this case.
I used temporary solution: Copy  ember-template-compiler.js of ember 2.0+ to node_modules / ember-template-compiler / vendor / , overwrites the same file.

**Comment by novtor** [comment]
hello, thank you for reply. For the moment I am not able to workaround this issue. What should I remove exactly? seems you wrote templateCompilerPath twice

**Comment by novtor** [comment]
it says 
{{#each content as |item|}}
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'STRING', 'NUMBER', 'BOOLEAN', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'EQUALS', 'DATA', 'SEP', got 'INVALID'

**Comment by novtor** [comment]
it is Ok, I have finally managed to do this. Thanks for the hint

**Comment by arminzia** [comment]
@leafrabbit Thanks for the tip, you're a life saver. I was struggling with this issue for the past few hours and it was driving me nuts! So the ember-template-compiler.js file in the node_modules directory was outdated, duh!

**Comment by ryansonshine** [comment]
Has there been any update with a new solution that doesn't involve copying over the ember-template-compiler.js from the ember folder for this issue?

**Comment by ycbb** [comment]
It is trouble really for copying file, but i'm not sure to get better solution now.
I think , fork it to modify ? I may not be able to do it about node.js.
However,if you work on Linux,what about the writing a shell script? Like this:

patch.sh

    #!/bin/bash
    mv ./node_modules/ember-template-compiler/vendor/ember-template-compiler.js ./node_modules/ember-template-compiler/vendor/ember-template-compiler.js.backup
    cp ./bower_components/ember/ember-template-compiler.js ./node_modules/ember-template-compiler/vendor/ember-template-compiler.js
    exit

unpatch.sh

    #!/bin/bash
    rm -rf ./node_modules/ember-template-compiler/
    npm update
    exit

By the way, I'm a Chinese. So sorry, my English is not good.  Maybe I spend a lot of times on looking for girls on my school ,it's more than studying. HaHa～～～～。

纵情哪般岁月，不堪回首少年时。

**Comment by leafrabbit** [comment]
It is trouble really for copying file, but i'm not sure to get better solution now.
I think , fork it to modify ? I may not be able to do it about node.js.
However,if you work on Linux,what about the writing a shell script? Like this:

patch.sh

    #!/bin/bash
    mv ./node_modules/ember-template-compiler/vendor/ember-template-compiler.js ./node_modules/ember-template-compiler/vendor/ember-template-compiler.js.backup
    cp ./bower_components/ember/ember-template-compiler.js ./node_modules/ember-template-compiler/vendor/ember-template-compiler.js
    exit

unpatch.sh

    #!/bin/bash
    rm -rf ./node_modules/ember-template-compiler/
    npm update
    exit
By the way, I'm a Chinese. So sorry, my English is not good. Maybe I spend a lot of times on looking for girls on my school ,it's more than studying. HaHa～～～～。

纵情哪般岁月，不堪回首少年时。

**Comment by zoltan-nz** [comment]
v1.0 of this package removed old dependencies and uses the official ember-template.compiler.js. Please let us know if you experience any problem with the new version.
