### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Creosteanu** [dgeb/grunt-ember-templates#87]
I have a micro amazon instance which when attempting to compile gives me a segmentation fault.

My project is relatively big, 387 templates.

Any idea how I could fix this?

**Comment by zoltan-nz** [comment]
@Creosteanu are you still experience this problem or it is solved meanwhile?

**Comment by Creosteanu** [comment]
We managed to solve the problem by segmenting our grunt task into smaller
bits.

The problem is likely still there.

Am I the only one who has experienced this?

On Sat, Apr 2, 2016 at 5:42 AM, Zoltan <notifications@github.com> wrote:

> @Creosteanu <https://github.com/Creosteanu> are you still experience this
> problem or it is solved meanwhile?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dgeb/grunt-ember-templates/issues/87#issuecomment-204639223>
>



-- 

*Radu Creosteanu*

Chief Technical Officer





fleetster by *Next Generation Mobility GmbH & Co. **KG*



M: +49 15 208 804 875

radu.creosteanu@fleetster.net



www.fleetster.de

**Comment by zoltan-nz** [comment]
@Creosteanu I guess it is possible to reproduce with a smoke test, I can try it out with generating some dummy list of templates... Maybe some memory leak... what was the version of the node.js?

**Comment by Creosteanu** [comment]
When this was happening we were using 0.11.13 if I am not mistaken.

This was only a problem when attempting to run on a micro aws instance.

The command was run as part of a batch grunt command to build the entire
app which also contained a grunt uglify. Once grunt ember templates was
separated from the uglify the problem went away.

Likely some memory management issue somewhere in there.

On Mon, Apr 4, 2016 at 1:30 PM, Zoltan <notifications@github.com> wrote:

> @Creosteanu <https://github.com/Creosteanu> I guess it is possible to
> reproduce with a smoke test, I can try it out with generating some dummy
> list of templates... Maybe some memory leak... what was the version of the
> node.js?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dgeb/grunt-ember-templates/issues/87#issuecomment-205255153>
>



-- 

*Radu Creosteanu*

Chief Technical Officer





fleetster by *Next Generation Mobility GmbH & Co. **KG*



M: +49 15 208 804 875

radu.creosteanu@fleetster.net



www.fleetster.de
