### ISSUE TITLE
Request for Maintainer

### ISSUE THREAD

**Issue by dgeb** [dgeb/grunt-ember-templates#88]
I'm no longer using grunt with any of my ember projects, so I'm probably not the best maintainer of this project. If anyone is interested in taking a more active role, please let me know!

**Comment by zoltan-nz** [comment]
Hi @dgeb, I have projects where I have to use grunt and this package. Slowly I will migrate to ember-cli. First of all,  the grunt based projects should be compatible with the ember-cli. I use your package for managing the templates. 

I can help to maintain and improve further, keep it compatible with the new version of grunt and ease the migration path to ember-cli. I guess, there are a few projects where grunt is the main build tool...

**Comment by zoltan-nz** [comment]
@dgeb I just updated the whole package. Removed old dependencies, and it would be compatible with Ember out of the box: https://github.com/dgeb/grunt-ember-templates/pull/90

It would be great if you could review it, please. Thank you. :)

**Comment by dgeb** [comment]
Fantastic, @zoltan-nz - thanks so much!

I've added you as a collaborator here and will add you as an owner on npm as well. Is your npm user account also zoltan-nz?

**Comment by zoltan-nz** [comment]
Wow, Thank You! :D 
My nickname on npm is `szines`: https://www.npmjs.com/~szines

**Comment by dgeb** [comment]
Well, thank you for picking this up. I hate to let projects languish, but it's hard to maintain them when I'm no longer using them myself. Of course, feel free to ping me if you want a second pair of eyes on something.

You're now an owner on npm as well. Publish away! :shipit:
