### ISSUE TITLE
Failure compiling templates with ember#2.11.0-beta.3

### ISSUE THREAD

**Issue by andyhot** [dgeb/grunt-ember-templates#94]
I started getting `ReferenceError: mainContext is not defined` when trying this with ember#2.11.0-beta.3 (btw, it works fine with ember#2.10.2)

It looks like the ember commit https://github.com/emberjs/ember.js/commit/e24e403656b9de62d55b1a3111e4eb309276d4b8#diff-5b2ea89606fd2097e9e17d66ae54ed51L2 (that simply cleaned up eslint warnings) introduced this  

As a workaround, one can still upgrade to ember#2.11.0-beta.3 by using the 'old' ember-template-compiler.js (the one included in ember#2.10.2)

**Comment by zoltan-nz** [comment]
Hey @andyhot, thanks for reporting this issue. I look into it now.

**Comment by andyhot** [comment]
Great!

I was looking at it myself - have a branch that showcases the problem at https://github.com/qrator/grunt-ember-templates/tree/topic-add-2.11-tests

**Comment by andyhot** [comment]
Found it... it appears to be an issue with ember. The fix is to remove the remaining mentions of mainContext from ember-template-compiler.js

I'll report it to them

**Comment by zoltan-nz** [comment]
@andyhot great, thank you... you are awesome! 

I kind of upgrade/simplify the test environment in this package to make it easy to add a new version in the future... ;)

**Comment by zoltan-nz** [comment]
@andyhot I see, you already extended tests for 2.11, we can merge that test in the main repo, and I continue the work on rewriting the test harness, so we don't have to duplicate the same code for each version.

**Comment by zoltan-nz** [comment]
@andyhot I merged your new tests and the new test runner setup here: https://github.com/zoltan-nz/grunt-ember-templates

From now, we have to add only the new version number to an array, and creating a new expected folder.

**Comment by andyhot** [comment]
Fixed in https://github.com/dgeb/grunt-ember-templates/issues/99
